import { Product, Category, FragranceNote } from '@/types';

export const categories: Category[] = [
  {
    id: 'women',
    name: "Women's Collection",
    slug: 'women',
    description: 'Timeless Elegance in Every Drop',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
  },
  {
    id: 'men',
    name: "Men's Collection",
    slug: 'men',
    description: 'Bold Character, Lasting Impression',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
  },
  {
    id: 'niche',
    name: 'Niche Collection',
    slug: 'niche',
    description: 'Rare Scents for Connoisseurs',
    image: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=800&q=80',
  },
];

export const products: Product[] = [
  // Aquad'or Signature Collection
  {
    id: 'signature',
    name: 'Signature',
    description: 'A masterful blend designed by Aquad\'or featuring bergamot, lavender, and nutmeg top notes, with leather and violet heart, resting on vetiver, patchouli, and oud base.',
    price: 29.99,
    category: 'men',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
    notes: {
      top: ['Bergamot', 'Lavender', 'Nutmeg', 'Mandarin Orange'],
      heart: ['Leather', 'Violet Leaf', 'Cedarwood', 'Clove'],
      base: ['Vetiver', 'Patchouli', 'Oud', 'Amber', 'Musk'],
    },
  },
  {
    id: 'cashmere-dubai-oud',
    name: 'Cashmere Dubai Oud',
    description: 'An opulent fusion of Kashmir wood, saffron, and black currant top notes, with rose and jasmine heart, finishing on oud, sandalwood, and vanilla.',
    price: 29.99,
    category: 'niche',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
    notes: {
      top: ['Kashmir Wood', 'Saffron', 'Black Currant', 'Plum'],
      heart: ['Rose', 'Jasmine', 'Kashmir Wood'],
      base: ['Oud', 'Kashmir Wood', 'Sandalwood', 'Vanilla', 'Musk'],
    },
  },
  {
    id: 'gold-yellow-vanilla-dubai',
    name: 'Gold Yellow Vanilla Dubai',
    description: 'A luxurious blend of white oud, Arabic vanilla, musk, and soft powdery notes creating an unforgettable signature.',
    price: 29.99,
    category: 'niche',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
    notes: {
      top: ['White Oud'],
      heart: ['Arabic Vanilla', 'Milk Mousse'],
      base: ['Musk', 'Amber', 'Sandalwood'],
    },
  },
  {
    id: 'troodos',
    name: 'Troodos',
    description: 'Inspired by Cyprus mountains, featuring rose, cedar, saffron with Cyprus cedrus and tobacco heart, resting on vanilla, tobacco, and incense.',
    price: 29.99,
    category: 'men',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
    notes: {
      top: ['Rose', 'Cedar', 'Saffron', 'Black Bee Honey'],
      heart: ['Cyprus Cedrus', 'Woodsy Notes', 'Tobacco', 'Cyprus Coffee'],
      base: ['Vanilla', 'Tobacco', 'Incense'],
    },
  },
  // Musk Collection
  {
    id: 'coconut-musk',
    name: 'Coconut Musk',
    description: 'Creamy, soft, and tropical — combining the milky sweetness of coconut with the clean, powdery warmth of musk.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  {
    id: 'pure-musk',
    name: 'Pure Musk',
    description: 'Crisp linen and gentle powder — bright, fresh, and softly clean with a silky, delicate finish.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  {
    id: 'rose-musk',
    name: 'Rose Musk',
    description: 'Elegant, romantic, and airy — fresh dewy roses and soft powdery musk with a smooth, lingering trail.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  {
    id: 'vanilla-musk',
    name: 'Vanilla Musk',
    description: 'Warm, soft, and inviting — sweet creamy vanilla with clean powdery musk, cozy and beautifully balanced.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  {
    id: 'sandal-musk',
    name: 'Sandal Musk',
    description: 'Soft, creamy, and comforting — warm smooth sandalwood with clean powdery musk, subtly sensual.',
    price: 29.99,
    category: 'niche',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  {
    id: 'pomegranate-musk',
    name: 'Pomegranate Musk',
    description: 'Rich and exotic with cinnamon and pomegranate top notes, oud and sandalwood heart, vanilla and musk base.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
    notes: {
      top: ['Cinnamon', 'Pomegranate'],
      heart: ['Oud', 'Sandalwood'],
      base: ['Vanilla', 'Musk'],
    },
  },
  {
    id: 'musk-al-tahara',
    name: 'Musk al Tahara',
    description: 'Traditional Arabic musk with white musk and cotton flower — pure, clean, and ethereal.',
    price: 29.99,
    category: 'women',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600&q=80',
    inStock: true,
    brand: "Aquad'or",
  },
  // Designer Inspirations
  {
    id: 'oud-acqua-di-parma',
    name: 'Oud by Acqua di Parma',
    description: 'Orange and bergamot top notes with oud, amyris, and coriander heart, leather and sandalwood base.',
    price: 29.99,
    category: 'niche',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    inStock: true,
    brand: 'Acqua di Parma',
    notes: {
      top: ['Orange', 'Calabrian Bergamot'],
      heart: ['Oud', 'Amyris', 'Coriander'],
      base: ['Leather', 'Sandalwood', 'Musk', 'Cedar', 'Patchouli'],
    },
  },
  {
    id: 'cuir-ysl',
    name: 'Cuir by Yves Saint Laurent',
    description: 'Rum, saffron, and ginger top notes with tobacco, black tea heart, leather and oud base.',
    price: 29.99,
    category: 'men',
    productType: 'perfume',
    size: '50ml',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
    inStock: true,
    brand: 'Yves Saint Laurent',
    notes: {
      top: ['Rum', 'Saffron', 'Ginger'],
      heart: ['Tobacco', 'Black Tea', 'Osmanthus'],
      base: ['Leather', 'Guaiac Wood', 'Oud'],
    },
  },
];

export const fragranceNotes: Record<string, FragranceNote[]> = {
  floral: [
    { name: 'Rose', icon: '🌹', color: '#FF6B9D', description: 'Velvety Damascus rose' },
    { name: 'Jasmine', icon: '🌸', color: '#F8F8FF', description: 'Night-blooming jasmine' },
    { name: 'Ylang-Ylang', icon: '🌼', color: '#FFE135', description: 'Exotic ylang-ylang' },
    { name: 'Tuberose', icon: '🌺', color: '#E6E6FA', description: 'Creamy tuberose' },
    { name: 'Violet', icon: '💜', color: '#8A2BE2', description: 'Powdery violet' },
    { name: 'Peony', icon: '🌷', color: '#FFB6C1', description: 'Fresh peony' },
    { name: 'Orange Blossom', icon: '🍊', color: '#FFA500', description: 'Citrus blossom' },
    { name: 'Lily', icon: '🌻', color: '#FFF8DC', description: 'Pure white lily' },
  ],
  fruity: [
    { name: 'Bergamot', icon: '🍋', color: '#32CD32', description: 'Earl Grey bergamot' },
    { name: 'Lemon', icon: '🍋', color: '#FFFF00', description: 'Sicilian lemon' },
    { name: 'Apple', icon: '🍏', color: '#90EE90', description: 'Crisp green apple' },
    { name: 'Peach', icon: '🍑', color: '#FFCBA4', description: 'Juicy white peach' },
    { name: 'Blackcurrant', icon: '🫐', color: '#800080', description: 'Tart blackcurrant' },
    { name: 'Pineapple', icon: '🍍', color: '#FFD700', description: 'Tropical pineapple' },
    { name: 'Pear', icon: '🍐', color: '#D1E231', description: 'Anjou pear' },
    { name: 'Mandarin', icon: '🍊', color: '#FF8C00', description: 'Sweet mandarin' },
  ],
  woody: [
    { name: 'Sandalwood', icon: '🪵', color: '#DEB887', description: 'Creamy sandalwood' },
    { name: 'Cedar', icon: '🌲', color: '#A0522D', description: 'Virginia cedarwood' },
    { name: 'Vetiver', icon: '🌿', color: '#8FBC8F', description: 'Haitian vetiver' },
    { name: 'Patchouli', icon: '🍂', color: '#654321', description: 'Dark patchouli' },
    { name: 'Oakmoss', icon: '🌳', color: '#9CAF88', description: 'Forest oakmoss' },
    { name: 'Pine', icon: '🎄', color: '#228B22', description: 'Mountain pine' },
  ],
  oriental: [
    { name: 'Oud', icon: '🔥', color: '#8B4513', description: 'Precious oud wood' },
    { name: 'Amber', icon: '✨', color: '#FFBF00', description: 'Warm amber resin' },
    { name: 'Incense', icon: '🕯️', color: '#696969', description: 'Sacred incense' },
    { name: 'Saffron', icon: '🌾', color: '#F4C430', description: 'Golden saffron' },
    { name: 'Cardamom', icon: '🫛', color: '#90EE90', description: 'Green cardamom' },
    { name: 'Cinnamon', icon: '🍂', color: '#D2691E', description: 'Ceylon cinnamon' },
  ],
  gourmand: [
    { name: 'Vanilla', icon: '🍦', color: '#F3E5AB', description: 'Madagascar vanilla' },
    { name: 'Chocolate', icon: '🍫', color: '#7B3F00', description: 'Dark chocolate' },
    { name: 'Coffee', icon: '☕', color: '#6F4E37', description: 'Roasted coffee' },
    { name: 'Caramel', icon: '🍯', color: '#AF6E4D', description: 'Burnt caramel' },
    { name: 'Honey', icon: '🍯', color: '#FFC649', description: 'Wildflower honey' },
    { name: 'Almond', icon: '🌰', color: '#FFDBCD', description: 'Sweet almond' },
  ],
};

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.slice(0, 6);
}
