INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('raghba-by-lattafa-perfumes', 'Raghba by Lattafa Perfumes', '', 29.99, NULL, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/5651d8b9-4129-409f-bf4e-fedb231a2643/image_Pippit_202506301816+%2853%29.jfif', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('24-carat-pure-gold-by-lattafa-perfumes', '24 Carat Pure Gold by Lattafa Perfumes', '', 29.99, NULL, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/5466a214-db1a-4860-ab90-7f6da0708f7d/image_Pippit_202507021156+-+2025-07-06T153205.581.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('pure-musk-by-lattafa-perfumes', 'Pure Musk by Lattafa Perfumes', '', 29.99, NULL, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/143822fa-1c9b-4e76-8c88-d9b71581a57a/image_Pippit_202507021156+-+2025-07-05T161907.056.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('yara-by-lattafa-perfumes', 'Yara by Lattafa Perfumes', '', 29.99, NULL, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/22ecef74-cd5b-4fc7-b86b-dad4bd30e133/image_Pippit_202506301816+%2855%29.jfif', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('khamrah-qahwa-by-lattafa-perfumes', 'Khamrah Qahwa by Lattafa Perfumes', '', 29.99, NULL, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6c997e8a-3cd7-4de0-894f-c40152fdc3e0/image_Pippit_202507021156+-+2025-07-05T161737.428.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ameer-al-oudh-intense-oud-by-lattafa-perfumes', 'Ameer Al Oudh Intense Oud by Lattafa Perfumes', '', 29.99, NULL, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/64e26778-22c3-4ef9-98f7-b2668b7935c7/image_Pippit_202507021156+-+2025-07-05T161444.235.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('asad-by-lattafa-perfumes', 'Asad by Lattafa Perfumes', '', 29.99, NULL, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/0dc10dc3-5989-44b9-a9e4-67caac482d20/image_Pippit_202506301816+%2856%29.jfif', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('rouat-al-oud-by-lattafa-perfumes', 'Rouat Al Oud by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 22.4, 22.4, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6911e301-391a-4d16-b1a1-e75660d6b026/image_Pippit_202508311301+%286%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ser-al-khulood-by-lattafa-perfumes', 'Ser Al Khulood by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 15.9, 15.9, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/8ef701e9-4952-4a76-9441-2bde04ecb9fc/image_Pippit_202508301210+%282%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('saud-by-asdaaf-lattafa-perfumes', 'Sa''ud by Asdaaf (Lattafa Perfumes)', 'We have it available in the original sealed 100 ml EDP package.', 21.5, 21.5, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/df2a12cb-bab8-43a9-92f9-a1d7729d725b/image_Pippit_202508291707+%283%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('breeze-by-lattafa-perfumes', 'Breeze by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 27.6, 27.6, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/14639bdd-0fbd-40be-b872-3792f45aba4f/image_Pippit_202509011438+%286%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('raw-human-by-lattafa-perfumes', 'Raw Human by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 34.5, 34.5, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/32c2689c-5366-41ee-81a9-4b51960e9325/image_Pippit_202509011438+%284%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('now-by-rave-lattafa-perfumes', 'Now by Rave (Lattafa Perfumes)', 'We have it available in the original sealed 100 ml EDP package.', 22.9, 22.9, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/908d7578-5514-4300-9ec5-448e2032b144/image_Pippit_202508301210+%2822%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('rava-luxur-by-lattafa-perfumes', 'Rava Luxuré by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package', 15.9, 15.9, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/4d58731b-14b3-416c-9094-7248fe043056/image_Pippit_202508291707.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('khanjar-by-lattafa-perfumes', 'Khanjar by Lattafa Perfumes', 'We have it available in the original sealed 85 ml EDP package.', 54.5, 54.5, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/9f386560-d798-444b-9da0-9d1bb56ba51c/image_Pippit_202508301210+%2827%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('nardo-red-by-rave-lattafa-perfumes', 'Nardo Red by Rave (Lattafa Perfumes)', 'Top Notes: Pineapple, Black Currant, Bergamot and Apple.', 22.5, 22.5, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/ecd6b110-071a-495f-9e72-c9a50c407894/image_Pippit_202508301210+%288%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('nardo-black-by-rave-lattafa-perfumes', 'Nardo Black by Rave (Lattafa Perfumes)', 'Top Notes: Bergamot, Black Currant and Apple.', 23.88, 23.88, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/8d1b07a2-26d8-465f-b905-0ffc87e1ff16/image_Pippit_202508311301+%282%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('al-jawhara-by-lattafa-perfumes', 'Al Jawhara by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 60, 60, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/3c62b582-a2af-43aa-a950-30ae54b1124a/image_Pippit_202508311301+%288%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('antique-by-lattafa-perfumes', 'Antique by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 59.9, 59.9, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/c5f3c1a1-bc50-4754-9e5d-57d3548cdc70/image_Pippit_202508311301+%2814%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('zikra-by-lattafa-perfumes', 'Zikra by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 60, 60, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/1765999609631-5EC33BK73K274ML3TCHR/313C6058-6389-487F-AD1C-113C424CEBA1.png', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('vintage-castle-by-lattafa-perfumes', 'Vintage Castle by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 60, 60, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/f0ef7cc7-924c-4e9a-b685-32f012f95b80/image_Pippit_202508301210+%2814%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('coastal-pour-femme-by-maison-alhambra-lattafa-perfumes', 'Coastal Pour Femme by Maison Alhambra (Lattafa Perfumes)', 'We have it available in the original sealed 100 ml EDP package.', 17.64, 17.64, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/eb11bfab-9059-4741-9845-a3fad4daf7f3/image_Pippit_202508301210+%2820%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('signatures-no-i-by-maison-alhambra-lattafa-perfumes', 'Signatures No I by Maison Alhambra (Lattafa Perfumes)', 'We have it available in the original sealed 50 ml EDP package.', 19.85, 19.85, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/270f3804-b231-4640-8d55-24c6dbe08187/image_Pippit_202508301210+%284%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('infini-oud-joyous-by-maison-alhambra-lattafa-perfumes', 'Infini Oud Joyous by Maison Alhambra (Lattafa Perfumes)', 'We have it available in the original sealed 100 ml EDP package.', 26, 26, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6212b759-63f7-466f-8b8a-021ccb99e3da/image_Pippit_202508301210+%2810%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('infini-oud-by-maison-alhambra-lattafa-perfumes', 'Infini Oud by Maison Alhambra (Lattafa Perfumes)', 'We have it available in the original sealed 100 ml EDP package.', 26, 26, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6365d8a5-a72c-4cfe-a6a2-dde6f5b13e89/image_Pippit_202508301210.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('oud-mood-reminiscence-silver-by-lattafa-perfumes', 'Oud Mood Reminiscence (Silver) by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 21.5, 21.5, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/23f39b79-14b4-4337-9ad9-cc3586fc1933/image_Pippit_202509011438+%282%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('raed-silver-by-lattafa-perfumes', 'Ra''ed Silver by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 21.5, 21.5, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/c1a0af26-7317-4ccb-b55e-52892fdc9fdf/image_Pippit_202508311301+%2810%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('fakhar-black-by-lattafa-perfumes', 'Fakhar Black by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 26.4, 26.4, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/ad3cede8-ed98-4fde-8e15-55b85e76aa9f/image_Pippit_202508311301+%2818%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('emaan-by-lattafa-perfumes', 'Emaan by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 27.5, 27.5, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/e36f5ac6-0601-46f2-84ff-1b40faad00c7/image_Pippit_202508301210+%2818%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('asad-zanzibar-by-lattafa-perfumes', 'Asad Zanzibar by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 29.9, 29.9, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/19b22f51-58a6-4181-848d-4e5046fa4332/image_Pippit_202508311301+%284%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('oud-mood-by-lattafa-perfumes', 'Oud Mood by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 30, 30, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6c24c8dd-a1c4-4e77-9336-72834a1a9e5c/image_Pippit_202508311301+%281%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('khalis-musk-pure-musk-by-lattafa-perfumes', 'Khalis Musk (Pure Musk) by Lattafa Perfumes', 'Fragrance Note: Pure Musk.', 17.9, 17.9, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/72b0ff59-2cbf-466f-99c3-46f97be9cf16/image_Pippit_202509011438.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('al-noble-wazeer-by-lattafa-perfumes', 'Al Noble Wazeer by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 25.9, 25.9, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/72a8d5e5-a587-4091-8179-d234a0e65b96/image_Pippit_202508301210+%2812%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('al-noble-safeer-by-lattafa-perfumes', 'Al Noble Safeer by Lattafa Perfumes', '', 25.9, 25.9, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/321e28db-6fcb-41ae-8646-57aeca13c840/image_Pippit_202508301210+%2816%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ana-abiyedh-rouge-by-lattafa-perfumes', 'Ana Abiyedh Rouge by Lattafa Perfumes', 'We have it available in the original sealed 60 ml EDP package.', 30, 30, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/ec0d1a89-677b-4b09-a9e0-e26763cec8e3/image_Pippit_202508311301+%2816%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ana-abiyedh-leather-by-lattafa-perfumes', 'Ana Abiyedh Leather by Lattafa Perfumes', 'We have it available in the original sealed 60 ml EDP package.', 30, 30, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/4654e191-a652-4215-ba2e-20ee42d69de0/image_Pippit_202508311301+%2812%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ramz-by-lattafa-perfumes', 'Ramz by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 16.9, 16.9, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/bff74ec6-3002-4970-9768-d4ed9ddb32d1/image_Pippit_202508301210+%286%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ajwad-by-lattafa-perfumes', 'Ajwad by Lattafa Perfumes', 'We have it available in the original sealed 60 ml EDP package.', 35, 35, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/b8009e94-0560-450d-bbc5-589dd120965d/image_Pippit_202509011438+%289%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ajwad-pink-to-pink-by-lattafa-perfumes', 'Ajwad Pink to Pink by Lattafa Perfumes', 'We have it available in the original sealed 60 ml EDP package.', 35, 35, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/a1fc00fc-d127-4b91-86fc-6c34dac3e74b/image_Pippit_202509011438+%2811%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('velvet-musk-by-lattafa-perfumes', 'Velvet Musk by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 20.99, 20.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/9af6bac6-64dc-44a4-81b0-d3f27fd1f85a/image_Pippit_202509011438+%2813%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('badee-al-oud-oud-for-glory-by-lattafa-perfumes', 'Bade''e Al Oud Oud for Glory by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 32.99, 32.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/2d9f8aa2-96cb-4473-ad99-f5f59018a1ba/image_Pippit_202509011438+%2815%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('badee-al-oud-amethyst-by-lattafa-perfumes', 'Bade''e Al Oud Amethyst by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 32.99, 32.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/1dd2d648-f61b-4ae8-af16-c58cc22719b9/image_Pippit_202509011438+%2817%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('badee-al-oud-honor-glory-by-lattafa-perfumes', 'Bade''e Al Oud Honor & Glory by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 32.99, 32.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/58e4baaf-6bfc-4b1c-8105-7e5a00a781c0/image_Pippit_202509091647.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('badee-al-oud-noble-blush-by-lattafa-perfumes', 'Bade''e Al Oud Noble Blush by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 35, 35, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/943bd321-6eb4-4926-aca7-706a01749e86/image_Pippit_202509091647+%282%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('eclaire-by-lattafa-perfumes', 'Eclaire by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 38.99, 38.99, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/fe8a156f-bb20-4ea8-aa0e-2bc160d2c859/image_Pippit_202509101514+%281%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('haya-by-lattafa-perfumes', 'Haya by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 27.5, 27.5, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/5f92fd5b-e39c-408f-b32d-1c4eb3152cb4/image_Pippit_202509101514+%283%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ana-abiyedh-by-lattafa-perfumes', 'Ana Abiyedh by Lattafa Perfumes', 'We have it available in the original sealed 60 ml EDP package.', 30, 30, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/6838f019-b719-4282-b2bc-25f7e90ceb7d/image_Pippit_202509121406+%281%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('ana-abiyedh-poudr-e-by-lattafa-perfumes', 'Ana Abiyedh Poudrée by Lattafa Perfumes', 'Middle Note: Musk.', 30, 30, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/1528c3ff-55d5-4f37-9685-d142c15923fa/image_Pippit_202509121406+%283%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('afeef-by-lattafa-perfumes', 'Afeef by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 40, 40, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/b72d9606-b5d9-43da-a1c2-c6dc543006b3/image_Pippit_202509121406+%285%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('the-kingdom-men-by-lattafa-perfumes', 'The Kingdom (Men) by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 30, 30, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/b1e6a590-28b7-4ff3-a2eb-4134a6134503/image_Pippit_202509261551.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('khamrah-qahwa-by-lattafa-perfumes', 'Khamrah Qahwa by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 39.99, 39.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/39636dc6-a6c4-4b4d-968d-46a0f5bea78c/image_Pippit_202509201633.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('fakhar-rose-by-lattafa-perfumes', 'Fakhar Rose by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 24.7, 24.7, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/c90eee44-e1ca-4c68-8135-8d475b1cdda2/image_Pippit_202509261551+%282%29.jpeg', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('sehr-by-lattafa-perfumes', 'Sehr by Lattafa Perfumes', 'Middle Notes: Akigalawood, Pomarose and Jasmine.', 48.99, 48.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/fa5c1b09-b1d5-4f03-b371-d83bf7fef205/image_Pippit_202509261551+%284%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('maahir-black-by-lattafa-perfumes', 'Maahir Black by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 32.99, 32.99, 'niche', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/d51cf4e2-9ef7-4073-b989-9fad1ce7d4b0/image_Pippit_202509261551+%288%29.jpeg', true, 'Lattafa Perfumes', 'unisex', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('maahir-legacy-by-lattafa-perfumes', 'Maahir Legacy by Lattafa Perfumes', 'We have it available in the original sealed 100 ml EDP package.', 33.3, 33.3, 'men', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/63aa4cd0-d8f2-44e5-9490-9380ae9995ac/image_Pippit_202509261551+%289%29.jpeg', true, 'Lattafa Perfumes', 'men', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();

INSERT INTO products (id, name, description, price, sale_price, category, product_type, size, image, in_stock, brand, gender, tags, created_at, updated_at) VALUES ('yara-tous-by-lattafa-perfumes', 'Yara Tous by Lattafa Perfumes', 'Base Notes: Vanilla, Musk and Cashmeran.', 30, 30, 'women', 'perfume', '100ml', 'https://images.squarespace-cdn.com/content/v1/66901f0f8865462c0ac066ba/1766027634987-0FWX0MYX5K1J5QSJWXJH/9EA27596-2F31-4169-AC19-38794F6C952B.png', true, 'Lattafa Perfumes', 'women', NULL, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, sale_price = EXCLUDED.sale_price, image = EXCLUDED.image, updated_at = NOW();